### ISSUE TITLE
Get data from an API

### ISSUE THREAD

**Issue by spences10** [Syknapse/My-Learning-Tracker#2]
Noticed on your checklist that you haven't retrieved data from an API

Check the linked video for a great guide 👍 

https://youtu.be/tUE2Nic21BA

**Comment by Syknapse** [comment]
Thanks for the feedback. I would like to understand better what you mean, how would an API help my checklist?

**Comment by spences10** [comment]
I saw it on your checklist

![screenshot_20171224-163259__01](https://user-images.githubusercontent.com/234708/34327888-46766444-e8c8-11e7-93d8-25a26c841b08.jpg)

**Comment by Syknapse** [comment]
Oh I get you. Thanks. I thought you were suggesting that I use an API for my checklist and I was confused. Thanks for sharing the video, it's on my soon to do list.
